### PR TITLE
Removed confusing and redundant lib/app.rb

### PR DESCRIPTION
**Pull request by hoovercj**
The cucumber tests don't reference this file and instead reference `app.rb` in the root of the directory. This file appears to be unnecessary and confusing.

### CODE REVIEW

**Comment by armandofox** [comment]
i think the cuke test may need revising, because i believe lib/ is the appropriate place for the file.  can someone double check this before merging this pull, to make sure the correct pull wouldn't be one that modifies the cuke test?

Armando Fox
Professor, Computer Science Division
Faculty Advisor, UC Berkeley MOOCLab
fox .at. cs .dot. berkeley .dot. edu
581 Soda Hall MC#1776, Berkeley, CA 94720-1776
+1.510.642.6820 / http://www.cs.berkeley.edu/~fox

TAKE MY CLASS FOR FREE VIA edX:  http://saas-class.org  
LIKE IT ON FACEBOOK:  http://facebook.com/saas-class
TRY MY BOOK (NOT FREE): http://beta.saasbook.info (goes with the course)

**Comment by hoovercj** [comment]
I made a [thread](https://courses.edx.org/courses/course-v1:BerkeleyX+CS169.1x+3T2015/discussion/forum/i4x-edx-templates-course-Empty/threads/5633ac00c7627726d000236a) in the saas course and other people have had issues with this file as well. Hopefully my warning will help other students, though, until something is fixed.

**Comment by juampi** [comment]
Even though lib/ may be the appropriate location for the app.rb file, the one that is currently there seems to be incomplete. The one in the root directory appears to be the correct one for completing the assignment.

So we could either revise the Cucumber tests and replace lib/app.rb with app.rb, or simply remove the former.

**Comment by tansaku** [comment]
@armandofox I guess in the ideal world we'd have CI giving us reports on whether any proposed changes like this were going to introduce other issues or failures ... we have the ci repos but at the moment they won't auto run on pull requests on this repo ... hmmm

**Pull request merged**
